from .reviews import Review

from pydantic import BaseModel, PrivateAttr

class Keyword(BaseModel):
    product_id: str
    keyword: str
    frequency: int
    sentiment: float # +-1
    embedding: list[float] | None = None

class LLMOutput(BaseModel):
    product_id: str
    keywords: list[Keyword]
    rating: float
    summary: str # Summary of the
    summary_embedding: list[float] | None = None # To be integrated


class Cluster(BaseModel):
    product_id: str
    gen_keyword: str # Keyword generated by k-means centroid of all embeddings.
    embedding: list[float]
    total_sentiment: float
    num_occur: int
    original_keywords: list[str] # ID's of the keywords which created this topic.
    